const std = @import("std");
const MinimalPHF = @import("minimal_perfect_hash.zig");

test "CHDMinimalPerfectHash" {
    const allocator = std.testing.allocator;

    var mphf = try MinimalPHF.init(allocator, &keys);
    defer mphf.deinit();

    for (keys) |key| {
        try std.testing.expect(mphf.getIndex(key) != null);
    }
}

// test "ComptimeCHDMinimalPerfectHash" {
//     const mphf = try MinimalPHF.comptimeInit(&keys);
//     for (keys) |key| {
//         try std.testing.expect(mphf.getIndex(key) != null);
//     }
// }

const keys = [_][]const u8{
    "apple",
    "banana",
    "cherry",
    "date",
    "elderberry",
    "fig",
    "grape",
    "honeydew",
    "kiwi",
    "lemon",
    "mango",
    "nectarine",
    "orange",
    "papaya",
    "quince",
    "raspberry",
    "strawberry",
    "tangerine",
    "ugli",
    "vanilla",
    "watermelon",
    "xigua",
    "yellowfruit",
    "zucchini",
    "avocado",
    "blueberry",
    "cantaloupe",
    "dragonfruit",
    "eggplant",
    "feijoa",
    "guava",
    "huckleberry",
    "jackfruit",
    "kumquat",
    "lychee",
    "mulberry",
    "noni",
    "olive",
    "pineapple",
    "quenepa",
    "rambutan",
    "starfruit",
    "tomato",
    "ume",
    "violetfruit",
    "wolfberry",
    "ximenia",
    "yangmei",
    "zinfandel",
    "carrot",
    "broccoli",
    "cauliflower",
    "spinach",
    "kale",
    "lettuce",
    "pumpkin",
    "squash",
    "yam",
    "beet",
    "radish",
    "turnip",
    "parsnip",
    "celery",
    "cucumber",
    "pepper",
    "onion",
    "garlic",
    "shallot",
    "chive",
    "leek",
    "pea",
    "bean",
    "lentil",
    "chickpea",
    "soybean",
    "edamame",
    "peanut",
    "almond",
    "cashew",
    "walnut",
    "pistachio",
    "pecan",
    "hazelnut",
    "macadamia",
    "brazilnut",
    "www.google.com",
    "www.facebook.com",
    "www.twitter.com",
    "www.linkedin.com",
    "www.github.com",
    "www.stackoverflow.com",
    "www.reddit.com",
    "www.quora.com",
    "https://openai.com",
    "https://developer.mozilla.org",
    "https://ziglang.org",
    "https://example.com",
    "https://mywebsite.com",
    "file://local/path/to/resource",
    "ftp://myserver.com/resource",
    "http://mywebsite.com/page",
    "admin",
    "user",
    "guest",
    "superuser",
    "root",
    "test",
    "alpha",
    "beta",
    "gamma",
    "delta",
    "epsilon",
    "theta",
    "sigma",
    "omega",
    "pi",
};
